POST http://localhost:8080/alumnos/primer-ano HTTP/1.1
Content-Type: application/json 

{
      "id": 4,
      "nombre": "Diego Lozano",
      "edad": 35,
      "DNI": 34678913,
      "Materia_Favorita": "Tecnologia Lactea"
}
###

PUT http://localhost:8080/alumnos/primer-ano/2 HTTP/1.1
Content-Type: application/json

{
      "id": 2,
      "nombre": "Manuel Lione Falso por id",
      "edad": 32,
      "DNI": 34668913,
      "Materia_Favorita": "Lengua"
}
###
PATCH http://localhost:8080/alumnos/primer-ano/2 HTTP/1.1
Content-Type:  application/json

{
  "edad": 19,
  "DNI": 44914669
}
###
DELETE http://localhost:8080/alumnos/primer-ano/3 HTTP/1.1
